version: 2
jobs:
  build:
    docker:
      - image: docker:17.06
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd && ls && ls ./automation && chmod +x ./automation/jenkins-build.sh && ./automation/jenkins-build.sh
