version: 2
jobs:
  build:
    docker:
      - image: docker:17.06
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd && ls && chmod +x ./automation/build.sh && ./automation/build.sh
